server {
    listen 80;
    server_name localhost;

    add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-eval' https://api.mapbox.com https://cdn.jsdelivr.net; style-src 'self' 'unsafe-inline' https://api.mapbox.com https://api.tiles.mapbox.com https://cdn.jsdelivr.net https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com https://cdn.jsdelivr.net; img-src 'self' blob: data: https://api.mapbox.com https://api.tiles.mapbox.com https://tarterware.com https://*.tarterware.com https://*.tarterware.info https://*.googleusercontent.com; connect-src 'self' https://*.amazonaws.com https://*.amazoncognito.com https://cdn.jsdelivr.net https://api.mapbox.com https://api.tiles.mapbox.com https://events.mapbox.com https://ipapi.co https://*.tarterware.info https://*.tarterware.com; worker-src 'self' blob:; child-src 'self' blob:;" always;
    add_header X-Frame-Options "DENY" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
